### ISSUE TITLE
TypeError: fetch failed - Error occurred prerendering page "/activity-logs"

### ISSUE THREAD

**Issue by k1enttt** [k1enttt/web-smart-water#13]
# Summary

Meet the issue after running `npm run build` at `mqtt` branch

# Standard debugging steps

## How to reproduce?

- Checkout to `mqtt` branch
- Run `npm run build` in the terminal
- Get the Type error

## Excepted behaviour

- Run `npm run build` normally and have no error

## Stacktrace

```
Generating static pages (1/8)  [=   ]TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async d (C:\Users\tathu\Documents\projs\web-smart-water\.next\server\app\activity-logs\page.js:18:3900)
    at async c (C:\Users\tathu\Documents\projs\web-smart-water\.next\server\app\activity-logs\page.js:18:4085) {
  cause: Error: connect ECONNREFUSED ::1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 3000
  },
  digest: '2427139486'
}
...
Error occurred prerendering page "/activity-logs". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async d (C:\Users\tathu\Documents\projs\web-smart-water\.next\server\app\activity-logs\page.js:18:3900)
    at async c (C:\Users\tathu\Documents\projs\web-smart-water\.next\server\app\activity-logs\page.js:18:4085)
 ✓ Generating static pages (8/8)

> Export encountered errors on following paths:
        /activity-logs/page: /activity-logs
```

# Other details

**Comment by k1enttt** [comment]
The code at getActivityLogs() function is misspelling url at fetch() (line 10, lib\activity-log.ts).

Just replace the "_" to "-".

## Old code
```javascript
const response: NextResponse = await fetch(`${baseApiUrl}/activity_logs`).then(
    (response) => response.json()
  );
```

## New code
```javascript
const response: NextResponse = await fetch(`${baseApiUrl}/activity-logs`).then(
    (response) => response.json()
  );
```

**Comment by k1enttt** [comment]
I just uncomment the code at log-table.tsx that i comment before. This should be closed
